
name: Windows exe deploy

on:
  push:
    branches: [ "master" ]

jobs:
    build:
      uses: inventvmsemipv/ivm-test-gui/.github/workflows/windows-exe.yml@master
      with:
         binary-artifact-name: ivm-gui-zip
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: ivm-gui-zip
            path: ${{ github.workspace }}/ivm-gui.zip
        - name: rsync deployments
          uses: burnett01/rsync-deployments@5.2
          with:
            switches: -avzr --delete --exclude="" --include="" --filter=""
            path: ivm-gui.zip
            remote_path: ${{ secrets.DEPLOY_PATH }}
            remote_host: ${{ secrets.DEPLOY_HOST }}
            remote_port: ${{ secrets.DEPLOY_PORT }}
            remote_user: ${{ secrets.DEPLOY_USER }}
            remote_key: ${{ secrets.DEPLOY_KEY }}
            remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}
